/** @type {import('tailwindcss').Config} */
module.exports = {
  mode: 'jit',
  content: ['./public/**/*.{html,js}'],
  theme: {
    fontSize: {
      xs: '0.64rem',
      sm: '0.8rem',
      base: '1rem',
      xl: '1.25rem',
      '2xl': '1.563rem',
      '3xl': '1.953rem',
      '4xl': '2.441rem',
      '5xl': '3.052rem',
      '6xl': '3.815rem',
      '7xl': '4.768rem',
      '8xl': '5.96rem',
      '9xl': '7.451rem',
    },
    fontFamily: {
      sans: ['Inter'],
    },
    colors: {
      transparent: 'transparent',
      white: '#ffffff',
      black: '#000000',
      light: {
        primary: '#4b6700',
        'on-primary': '#ffffff',
        'primary-container': '#b8f600',
        'on-primary-container': '#141f00',
        'primary-fixed': '#b8f600',
        'on-primary-fixed': '#141f00',
        'primary-fixed-dim': '#a1d800',
        'on-primary-fixed-variant': '#384e00',
        secondary: '#5033ff',
        'on-secondary': '#ffffff',
        'secondary-container': '#e3dfff',
        'on-secondary-container': '#140067',
        'secondary-fixed': '#e3dfff',
        'on-secondary-fixed': '#140067',
        'secondary-fixed-dim': '#c5c0ff',
        'on-secondary-fixed-variant': '#3700e1',
        tertiary: '#795900',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#ffdf9e',
        'on-tertiary-container': '#261a00',
        'tertiary-fixed': '#ffdf9e',
        'on-tertiary-fixed': '#261a00',
        'tertiary-fixed-dim': '#fbbd00',
        'on-tertiary-fixed-variant': '#5b4300',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#410002',
        outline: '#76786b',
        background: '#fefcf4',
        'on-background': '#1b1c17',
        surface: '#fbf9f1',
        'on-surface': '#1b1c17',
        'surface-variant': '#e2e4d4',
        'on-surface-variant': '#45483c',
        'inverse-surface': '#30312c',
        'inverse-on-surface': '#f2f1e9',
        'inverse-primary': '#a1d800',
        shadow: '#000000',
        'surface-tint': '#4b6700',
        'outline-variant': '#c6c8b9',
        scrim: '#000000',
        'surface-container-highest': '#e4e3db',
        'surface-container-high': '#eae8e0',
        'surface-container': '#efeee6',
        'surface-container-low': '#f5f4ec',
        'surface-container-lowest': '#ffffff',
        'surface-bright': '#fbf9f1',
        'surface-dim': '#dbdad2',
      },
      dark: {
        primary: '#a1d800',
        'on-primary': '#263500',
        'primary-container': '#384e00',
        'on-primary-container': '#b8f600',
        'primary-fixed': '#b8f600',
        'on-primary-fixed': '#141f00',
        'primary-fixed-dim': '#a1d800',
        'on-primary-fixed-variant': '#384e00',
        secondary: '#c5c0ff',
        'on-secondary': '#2500a2',
        'secondary-container': '#3700e1',
        'on-secondary-container': '#e3dfff',
        'secondary-fixed': '#e3dfff',
        'on-secondary-fixed': '#140067',
        'secondary-fixed-dim': '#c5c0ff',
        'on-secondary-fixed-variant': '#3700e1',
        tertiary: '#fbbd00',
        'on-tertiary': '#402d00',
        'tertiary-container': '#5b4300',
        'on-tertiary-container': '#ffdf9e',
        'tertiary-fixed': '#ffdf9e',
        'on-tertiary-fixed': '#261a00',
        'tertiary-fixed-dim': '#fbbd00',
        'on-tertiary-fixed-variant': '#5b4300',
        error: '#ffb4ab',
        'on-error': '#690005',
        'error-container': '#93000a',
        'on-error-container': '#ffdad6',
        outline: '#909284',
        background: '#1b1c17',
        'on-background': '#e4e3db',
        surface: '#13140f',
        'on-surface': '#c8c7bf',
        'surface-variant': '#45483c',
        'on-surface-variant': '#c6c8b9',
        'inverse-surface': '#e4e3db',
        'inverse-on-surface': '#1b1c17',
        'inverse-primary': '#4b6700',
        shadow: '#000000',
        'surface-tint': '#a1d800',
        'outline-variant': '#45483c',
        scrim: '#000000',
        'surface-container-highest': '#343530',
        'surface-container-high': '#2a2a25',
        'surface-container': '#1f201b',
        'surface-container-low': '#1b1c17',
        'surface-container-lowest': '#0e0f0a',
        'surface-bright': '#393a34',
        'surface-dim': '#13140f',
      },
    },
    extend: {
      screens: {
        xs: '1px',
        '3xl': '1920px',
      },
    },
  },
  plugins: [
    require('@martijn.cuppens/tailwindcss-fluid')({
      minimum: 1, // Minimum size that needs fluid rescaling (in rem).
      breakpoint: 1200, // Max screen width where the fluid rescaling is applied to (in px).
      factor: 100, // Strength of resizing.
      twoDimensional: false, // Set to true if you want to resize to the smallest size of your device.
      unitPrecision: 5, // Rounding accuracy for calculated fluid resizing.
      remValue: 16, // Value of 1rem, needed for calculations.
    }),
  ],
}
